server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/school?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 3831

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml